spring:
  application:
    name: Blog

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
         format_sql: true